In [7]:
# Importamos Numpy 
import numpy as np

In [10]:
# Importamos el archivo que contiene la data. Definimos el delimitador como "," debido a que es un csv. Usamos el parámetro skiprows para saltarnos la primera línea que contiene los encabezados
cab_arr = np.loadtxt("nyc_taxis.csv", delimiter=",", skiprows=1)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [14]:
# Primer ejercicio: calcular la velocidad promedio de los taxis. Como no existe la velocidad debemos calcularla a partir de las columnas de tiempo y distancia- Primero seleccionamos todas las filas. Luego dividimos eso por el tiempo. En nuestro arreglo original el tiempo viene en segundos por lo que debemos convertirlo en horas
speed = cab_arr[:, 7] / ((cab_arr[:, 8])/3600) 

# Luego para encontrar la velocidad media
mean_speed = speed.mean()

32.24258580925573


In [21]:
# Segundo ejercicio: calcular la cantidad de viajes realizados en febrero

# Aquí seleccionamos sólo las filas de los viajes que se hicieron en febrero, además sólo seleccionamos una columna (la segunda)
trips_on_february = cab_arr[cab_arr[:, 1] == 2, 1]

# Luego con shape obtenemos la nueva forma del arreglo (obteniéndose una tupla de filas y columnas). Por lo tanto obtenemos el número de filas y esta es la cantidad de viajes en febrero
print(trips_on_february.shape[0])

13333


In [23]:
# Tercer ejercicio: calcular el número de viajes donde la propina fue mayor a 50. Es similar al ejercicio anterior, nótese que tal como en el caso anterior no es necesario obtener sólo una columna
tips_above_50 = cab_arr[cab_arr[:, 12] > 50]

print(tips_above_50.shape[0])

16
