In [7]:
# Importamos Numpy 
import numpy as np

In [10]:
# Importamos el archivo que contiene la data. Definimos el delimitador como "," debido a que es un csv. Usamos el parámetro skiprows para saltarnos la primera línea que contiene los encabezados
cab_arr = np.loadtxt("nyc_taxis.csv", delimiter=",", skiprows=1)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]
